### ISSUE TITLE
Caching of poetry dependency does not quite work yet

### ISSUE THREAD

**Issue by t-ober** [ie3-institute/psdm-analysis#18]
```
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'poetry'
```

This does not work as expected yet. Find out why.
